### ISSUE TITLE
Comm link creation goes nowhere

### ISSUE THREAD

**Issue by AndrewMC6** [mnit-rtmc/iris#46]
Attempting to add a DMS to a new installation, following the step-by-step on the web page I enter a name for the comm link and when I click create it doesn't appear in the table as indicated in the step-by-step it appears to just vanish

**Comment by DougLau-MNIT** [comment]
This issue should be fixed in 5.29.

**Comment by jlstanley-git** [comment]
You'll need to run the migrate-5.29.sql script to include the database
changes before you can run ver. 5.29.  (I recommend doing a database backup
first just to be safe.)

... John Stanley

**Comment by AndrewMC6** [comment]
Hi John,

Pardon my ignorance here but I have been fighting with trying to get this sql script to run for a while now. I keep getting various exceptions, that resource_type already exists. I changed the file to “create table if not exists” and successfully skipped that line however I’m not stuck again where it’s saying sonar_type doesn’t exist.

Mind you this is a completely fresh install for us to demo this software so 5.29 is the first instance to run on this machine so is it possible there isn’t anything for it to ‘migrate’?


Andrew Constantine
Intelligent Transportation System Coordinator

Maine Turnpike Authority
2360 Congress Street
Portland, ME 04102
Tel: 207-482-8236
Cell: 207-239-6008
***@***.******@***.***>

[https://d3lvmlls43bhrc.cloudfront.net/pitch/images/Cu5D9CdFdCaDqDRheBeWP6.png]

[FB]<https://www.facebook.com/MaineTurnpikeAuthority/>  [twitter] <https://twitter.com/MaineTurnpike>   [instagram] <https://www.instagram.com/milesthemaineturnpikemoose/?hl=en>   [Youtube_1] <https://www.youtube.com/user/MaineTurnpike>

**Comment by DougLau** [comment]
The migrate script is only needed to upgrade from version 5.28.  If there's nothing in the database, you can just start from the template:
```
dropdb tms
createdb tms
psql tms -f /var/lib/iris/sql/tms-template.sql
```

**Comment by AndrewMC6** [comment]
I was able to get it to drop the database, create and run that script. However iris still will not start, saying in stderr that the database versions don't match. I looked in the contents of tms-template and I don't see right off where the database version is defined. Perhaps that wasn't updated with the latest version?

**Comment by DougLau** [comment]
You are right, sorry about that.
That can be fixed with this sql:
```
UPDATE iris.system_attribute SET value = '5.29.0' WHERE name = 'database_version';
```

**Comment by AndrewMC6** [comment]
Iris is now running. The comm link creation going nowhere is still occurring. I'm trying to add a comm link with x.x.x.x and x.x.x.x:xxx neither successfully add a link.
